sudo: false

language:
  - cpp

branches:
  only:
    - master

os:
  - linux

script:
  - make

after_success:
  - ./main
  - ./main --version
  - ./main --my_flag
  - ./main --my_flag=1
  - ./main --my_flag=0
  - ./main --my_flag 1
  - ./main --my_flag 0
  - ./main --fake_arg
  - ./main --help
