sudo: false

language:
  - cpp

branches:
  only:
    - master

os:
  - linux

script:
  - make

after_success:
  - ./main
  - ./main --verbose
  - ./main --verbose=1
  - ./main --verbose=0
  - ./main --verbose 1
  - ./main --verbose 0
  - ./main --verbose 0 --verbose
  - ./main --fake_arg
  - ./main --help
